language: node_js

# Keep in sync with Dockerfile and createBinaries.js
node_js: '10.15.1'

services:
  - docker

addons:
  sonarqube:
    organization: "schnatterer-github"

cache:
    directories:
      - "node_modules"
      - '$HOME/.sonar/cache'
    yarn: true

install:
  - yarn install

script:
  - yarn test
  - sonar-scanner
  - docker build --no-cache -t dsdl .
  # Do some basic sanity checks with the container
  - echo $(docker run --rm dsdl audio --user someuser -o /dsdl http://diskstation/photo) | grep Password