name: Test scripts on push
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: yarn install
      - run: yarn test
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: docker build --no-cache -t dsdl .
      # Do some basic sanity checks with the container
      - run: echo $(docker run --rm dsdl audio --user someuser -o /dsdl http://diskstation/photo) | grep Password
