name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting with SonarCloud
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          # Keep in sync with Dockerfile and createBinaries.js
          node-version: '14'
      - run: yarn install
      - run: yarn test
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: docker build --no-cache -t dsdl .
      # Do some basic sanity checks with the container
      - run: echo $(docker run --rm dsdl audio --user someuser -o /dsdl http://diskstation/photo) | grep Password
